from bot import CMD_INDEX

class _BotCommands:
    def __init__(self) -> None:
        self.StartCommand = f'xdddvuuu{CMD_INDEX}'
        self.MirrorCommand = f'zqqqhj{CMD_INDEX}'
        self.UnzipMirrorCommand = f'unzipx{CMD_INDEX}'
        self.ZipMirrorCommand = f'zipx{CMD_INDEX}'
        self.CancelMirror = f'cancelx{CMD_INDEX}'
        self.CancelAllCommand = f'cancelallx{CMD_INDEX}'
        self.ListCommand = f'dlkghgu{CMD_INDEX}'
        self.SearchCommand = f'sea{CMD_INDEX}'
        self.StatusCommand = f'statushfjfjx{CMD_INDEX}'
        self.AuthorizedUsersCommand = f'users{CMD_INDEX}'
        self.AuthorizeCommand = f'authorize{CMD_INDEX}'
        self.UnAuthorizeCommand = f'unauthorize{CMD_INDEX}'
        self.AddSudoCommand = f'addsudo{CMD_INDEX}'
        self.RmSudoCommand = f'rmsudo{CMD_INDEX}'
        self.PingCommand = f'p{CMD_INDEX}'
        self.RestartCommand = f'restart{CMD_INDEX}'
        self.StatsCommand = f'statsxvfjg{CMD_INDEX}'
        self.HelpCommand = f'htp{CMD_INDEX}'
        self.LogCommand = f'logx{CMD_INDEX}'
        self.CloneCommand = f'clonex{CMD_INDEX}'
        self.CountCommand = f'countx{CMD_INDEX}'
        self.WatchCommand = f'watchhgggx{CMD_INDEX}'
        self.ZipWatchCommand = f'zipwathhgggchx{CMD_INDEX}'
        self.DeleteCommand = f'delx{CMD_INDEX}'
        self.ShellCommand = f'shellx{CMD_INDEX}'
        self.ExecHelpCommand = f'exechelp{CMD_INDEX}'
        self.LeechSetCommand = f'leechsehhhhhtx{CMD_INDEX}'
        self.SetThumbCommand = f'setthhhhumbx{CMD_INDEX}'
        self.LeechCommand = f'leechhhhhx{CMD_INDEX}'
        self.UnzipLeechCommand = f'unzipljjjjjeechx{CMD_INDEX}'
        self.ZipLeechCommand = f'zipleejjjjjchx{CMD_INDEX}'
        self.LeechWatchCommand = f'leechwahhhhhhtchx{CMD_INDEX}'
        self.LeechZipWatchCommand = f'leechzjhhhhhipwatchx{CMD_INDEX}'
        
BotCommands = _BotCommands()
